name: sentiment
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - click=7.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - flask=1.1.1
  - gmp=6.1.2
  - importlib_metadata=0.23
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - itsdangerous=1.1.0
  - jedi=0.15.1
  - jinja2=2.10.3
  - json5=0.8.5
  - jsonschema=3.1.1
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - more-itertools=7.2.0
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nltk=3.4.4
  - notebook=6.0.2
  - openssl=1.1.1d
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pyrsistent=0.15.4
  - python=3.7.5
  - python-dateutil=2.8.1
  - pyzmq=18.1.0
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=41.6.0
  - six=1.13.0
  - sqlite=3.30.1
  - terminado=0.8.2
  - testpath=0.4.2
  - textblob=0.15.3
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11

